// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB7a5Ej1x1hi04E9t7ARNK4OV8xRM_kZ4',
    appId: '1:1087466781469:web:a448a5c9c49962218b7ff4',
    messagingSenderId: '1087466781469',
    projectId: 'infants-corners',
    authDomain: 'infants-corners.firebaseapp.com',
    storageBucket: 'infants-corners.appspot.com',
    measurementId: 'G-ML534CEHKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBFlAbsSJ7kn3Qv7St9E6QugPc0h6rDI',
    appId: '1:1087466781469:android:c0815078735153378b7ff4',
    messagingSenderId: '1087466781469',
    projectId: 'infants-corners',
    storageBucket: 'infants-corners.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVPUs_QKByiFpbyevDNEZeJ1Q6n45yn0',
    appId: '1:1087466781469:ios:22608e0bccdffc2d8b7ff4',
    messagingSenderId: '1087466781469',
    projectId: 'infants-corners',
    storageBucket: 'infants-corners.appspot.com',
    iosBundleId: 'com.example.infantCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVPUs_QKByiFpbyevDNEZeJ1Q6n45yn0',
    appId: '1:1087466781469:ios:7b56e6264dc8bddd8b7ff4',
    messagingSenderId: '1087466781469',
    projectId: 'infants-corners',
    storageBucket: 'infants-corners.appspot.com',
    iosBundleId: 'com.example.infantCorner.RunnerTests',
  );
}
